import React from 'react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { act, fireEvent, render, screen, waitFor } from '@testing-library/react';
import AiSettings from '../src/components/AiSettings';
import { AI_DEFAULT_MODELS, DEFAULT_AI_MODEL, DEFAULT_AI_PROVIDER } from '../src/lib/aiTypes';
import type { AiStatus } from '../src/lib/aiTypes';

const api = vi.hoisted(() => ({ get: vi.fn(), model: vi.fn(), connect: vi.fn(), disconnect: vi.fn() }));
vi.mock('../src/lib/aiClient', () => ({ getAiStatus: api.get, setAiModel: api.model, connectAi: api.connect, disconnectAi: api.disconnect }));
const current: AiStatus = { configured: true, provider: 'openai', model: 'gpt-5.4-mini', source: 'session' };
const next: AiStatus = { ...current, model: 'gpt-4.1-mini' };
const disconnected: AiStatus = { configured: false, provider: DEFAULT_AI_PROVIDER, model: DEFAULT_AI_MODEL, source: 'none' };
const claude: AiStatus = { ...disconnected, configured: true, source: 'session' };
const onStatus = vi.fn(), onEnabled = vi.fn();
beforeEach(() => { vi.clearAllMocks(); api.model.mockResolvedValue(next); api.get.mockResolvedValue(current); });

async function ready() { await waitFor(() => expect((screen.getByRole('combobox', { name: 'AI model' }) as HTMLSelectElement).disabled).toBe(false)); }

describe('AI provider and model selection', () => {
  it('defaults new connections to Claude Haiku 4.5 and sends the selected provider', async () => {
    api.get.mockResolvedValue(disconnected);
    api.connect.mockResolvedValue(claude);
    render(<AiSettings status={disconnected} enabled={false} onStatus={onStatus} onEnabled={onEnabled}/>);
    await ready();
    expect((screen.getByRole('combobox', { name: 'AI provider' }) as HTMLSelectElement).value).toBe('anthropic');
    expect((screen.getByRole('combobox', { name: 'AI model' }) as HTMLSelectElement).value).toBe('claude-haiku-4-5-20251001');
    expect(screen.getByRole('link', { name: 'Create or manage an Anthropic API key' }).getAttribute('href')).toBe('https://console.anthropic.com/settings/keys');
    expect(screen.getByText(/forgotten when the server restarts/)).toBeTruthy();
    fireEvent.change(screen.getByLabelText('Anthropic API key'), { target: { value: ' test-claude-key ' } });
    fireEvent.click(screen.getByRole('button', { name: 'Connect and enable AI' }));
    await waitFor(() => expect(api.connect).toHaveBeenCalledWith('test-claude-key', DEFAULT_AI_MODEL, expect.any(AbortSignal), 'anthropic'));
    expect((screen.getByLabelText('Anthropic API key') as HTMLInputElement).value).toBe('');
    expect(onStatus).toHaveBeenCalledWith(claude);
    expect(onEnabled).toHaveBeenCalledExactlyOnceWith(true);
    expect(screen.getByRole('status').textContent).toContain('Model access checked.');
    expect(screen.getByRole('status').textContent).toContain('still requires available API credit');
  });
  it('clears the entered key and resets the model when the form provider changes', async () => {
    api.get.mockResolvedValue(disconnected);
    api.connect.mockResolvedValue(next);
    render(<AiSettings status={disconnected} enabled={false} onStatus={onStatus} onEnabled={onEnabled}/>);
    await ready();
    fireEvent.change(screen.getByLabelText('Anthropic API key'), { target: { value: 'test-claude-key' } });
    fireEvent.change(screen.getByRole('combobox', { name: 'AI model' }), { target: { value: 'custom' } });
    fireEvent.change(screen.getByRole('textbox', { name: 'Custom AI model' }), { target: { value: 'custom-claude-model' } });
    fireEvent.change(screen.getByRole('combobox', { name: 'AI provider' }), { target: { value: 'openai' } });
    expect((screen.getByLabelText('OpenAI API key') as HTMLInputElement).value).toBe('');
    expect(screen.queryByLabelText('Anthropic API key')).toBeNull();
    expect((screen.getByRole('combobox', { name: 'AI model' }) as HTMLSelectElement).value).toBe(AI_DEFAULT_MODELS.openai);
    expect(screen.queryByRole('textbox', { name: 'Custom AI model' })).toBeNull();
    expect(screen.getByRole('link', { name: 'Create or manage an OpenAI API key' }).getAttribute('href')).toBe('https://platform.openai.com/api-keys');
    expect(api.connect).not.toHaveBeenCalled();
    expect(api.disconnect).not.toHaveBeenCalled();
    fireEvent.change(screen.getByLabelText('OpenAI API key'), { target: { value: 'test-openai-key' } });
    fireEvent.click(screen.getByRole('button', { name: 'Connect and enable AI' }));
    await waitFor(() => expect(api.connect).toHaveBeenCalledWith('test-openai-key', AI_DEFAULT_MODELS.openai, expect.any(AbortSignal), 'openai'));
  });
  it('keeps the active provider and model when a replacement connection fails', async () => {
    api.connect.mockRejectedValueOnce(new Error('Anthropic could not authorise this key or model.'));
    render(<AiSettings status={current} enabled={true} onStatus={onStatus} onEnabled={onEnabled}/>);
    await ready();
    fireEvent.change(screen.getByRole('combobox', { name: 'AI provider' }), { target: { value: 'anthropic' } });
    expect(screen.getByText('OpenAI configured')).toBeTruthy();
    expect(screen.getByText(/New requests use OpenAI/)).toBeTruthy();
    expect(screen.getByText(/current OpenAI connection stays active/)).toBeTruthy();
    fireEvent.change(screen.getByLabelText('Anthropic API key'), { target: { value: 'invalid-claude-key' } });
    fireEvent.click(screen.getByRole('button', { name: 'Connect and enable AI' }));
    expect((await screen.findByRole('alert')).textContent).toContain('could not authorise');
    expect(screen.getByText('OpenAI configured')).toBeTruthy();
    expect(screen.getByText(current.model)).toBeTruthy();
    expect(onStatus).not.toHaveBeenCalled();
    expect(onEnabled).not.toHaveBeenCalled();
    expect(api.disconnect).not.toHaveBeenCalled();
    expect(api.model).not.toHaveBeenCalled();
  });
  it('disables all connection controls while a replacement is pending', async () => {
    let resolve!: (value: AiStatus) => void;
    api.connect.mockImplementation(() => new Promise(r => { resolve = r; }));
    render(<AiSettings status={current} enabled={true} onStatus={onStatus} onEnabled={onEnabled}/>);
    await ready();
    fireEvent.change(screen.getByRole('combobox', { name: 'AI provider' }), { target: { value: 'anthropic' } });
    fireEvent.change(screen.getByLabelText('Anthropic API key'), { target: { value: 'test-claude-key' } });
    fireEvent.click(screen.getByRole('button', { name: 'Connect and enable AI' }));
    expect((screen.getByRole('combobox', { name: 'AI provider' }) as HTMLSelectElement).disabled).toBe(true);
    expect((screen.getByRole('combobox', { name: 'AI model' }) as HTMLSelectElement).disabled).toBe(true);
    expect((screen.getByLabelText('Anthropic API key') as HTMLInputElement).disabled).toBe(true);
    expect((screen.getByRole('checkbox') as HTMLInputElement).disabled).toBe(true);
    expect((screen.getByRole('button', { name: 'Disconnect AI' }) as HTMLButtonElement).disabled).toBe(true);
    expect(onStatus).not.toHaveBeenCalled();
    await act(async () => resolve(claude));
    expect(onStatus).toHaveBeenCalledWith(claude);
    expect(onEnabled).toHaveBeenCalledExactlyOnceWith(true);
    expect(api.disconnect).not.toHaveBeenCalled();
  });
  it('ignores a closed dialog’s late replacement connection', async () => {
    let resolve!: (value: AiStatus) => void;
    api.connect.mockImplementation(() => new Promise(r => { resolve = r; }));
    const { unmount } = render(<AiSettings status={current} enabled={true} onStatus={onStatus} onEnabled={onEnabled}/>);
    await ready();
    fireEvent.change(screen.getByRole('combobox', { name: 'AI provider' }), { target: { value: 'anthropic' } });
    fireEvent.change(screen.getByLabelText('Anthropic API key'), { target: { value: 'test-claude-key' } });
    fireEvent.click(screen.getByRole('button', { name: 'Connect and enable AI' }));
    const signal = api.connect.mock.calls[0][2] as AbortSignal;
    // Closing the dialog aborts the request even if a transport resolves later.
    unmount();
    expect(signal.aborted).toBe(true);
    await act(async () => resolve(claude));
    expect(onStatus).not.toHaveBeenCalled();
    expect(onEnabled).not.toHaveBeenCalled();
  });
  it('changes model with the existing key only after access succeeds and preserves the paused setting', async () => {
    let resolve!: (value: AiStatus) => void;
    api.model.mockImplementation(() => new Promise(r => { resolve = r; }));
    render(<AiSettings status={current} enabled={false} onStatus={onStatus} onEnabled={onEnabled}/>);
    expect(screen.queryByLabelText('OpenAI API key')).toBeNull();
    await ready();
    fireEvent.change(screen.getByRole('combobox', { name: 'AI model' }), { target: { value: 'gpt-4.1-mini' } });
    fireEvent.click(screen.getByRole('button', { name: 'Use selected model' }));
    expect(api.model).toHaveBeenCalledWith('gpt-4.1-mini', expect.any(AbortSignal));
    expect(onStatus).not.toHaveBeenCalled();
    expect((screen.getByRole('combobox', { name: 'AI model' }) as HTMLSelectElement).disabled).toBe(true);
    await act(async () => resolve(next));
    expect(onStatus).toHaveBeenCalledWith(next);
    expect(onEnabled).not.toHaveBeenCalled();
    expect(screen.getByRole('status').textContent).toContain('Model changed to gpt-4.1-mini');
  });
  it('keeps the active model and connection on failure and allows a retry', async () => {
    api.model.mockRejectedValueOnce(new Error('OpenAI could not authorise this key or model.'));
    render(<AiSettings status={current} enabled={true} onStatus={onStatus} onEnabled={onEnabled}/>);
    await ready();
    fireEvent.change(screen.getByRole('combobox', { name: 'AI model' }), { target: { value: 'gpt-4.1-mini' } });
    fireEvent.click(screen.getByRole('button', { name: 'Use selected model' }));
    expect((await screen.findByRole('alert')).textContent).toContain('could not authorise');
    expect(screen.getByText('gpt-5.4-mini')).toBeTruthy();
    expect(onStatus).not.toHaveBeenCalled();
    expect(api.disconnect).not.toHaveBeenCalled();
    fireEvent.click(screen.getByRole('button', { name: 'Use selected model' }));
    await waitFor(() => expect(onStatus).toHaveBeenCalledWith(next));
  });
  it('blocks unchanged or busy model updates', async () => {
    const props = { status: current, enabled: true, onStatus, onEnabled };
    const { rerender } = render(<AiSettings {...props}/>);
    await ready();
    expect((screen.getByRole('button', { name: 'Use selected model' }) as HTMLButtonElement).disabled).toBe(true);
    fireEvent.change(screen.getByRole('combobox', { name: 'AI model' }), { target: { value: 'gpt-4.1-mini' } });
    rerender(<AiSettings {...props} busy/>);
    expect((screen.getByRole('combobox', { name: 'AI provider' }) as HTMLSelectElement).disabled).toBe(true);
    expect((screen.getByRole('button', { name: 'Disconnect AI' }) as HTMLButtonElement).disabled).toBe(true);
    expect((screen.getByRole('checkbox') as HTMLInputElement).disabled).toBe(true);
    fireEvent.click(screen.getByRole('button', { name: 'Use selected model' }));
    expect(api.model).not.toHaveBeenCalled();
  });
  it('accepts a custom model and synchronises a changed active model', async () => {
    const { rerender } = render(<AiSettings status={current} enabled={true} onStatus={onStatus} onEnabled={onEnabled}/>);
    await ready();
    fireEvent.change(screen.getByRole('combobox', { name: 'AI model' }), { target: { value: 'custom' } });
    expect((screen.getByRole('button', { name: 'Use selected model' }) as HTMLButtonElement).disabled).toBe(true);
    fireEvent.change(screen.getByRole('textbox', { name: 'Custom AI model' }), { target: { value: ' gpt-4.1-mini-2025-04-14 ' } });
    fireEvent.click(screen.getByRole('button', { name: 'Use selected model' }));
    await waitFor(() => expect(api.model).toHaveBeenCalledWith('gpt-4.1-mini-2025-04-14', expect.any(AbortSignal)));
    rerender(<AiSettings status={next} enabled={true} onStatus={onStatus} onEnabled={onEnabled}/>);
    await ready();
    expect((screen.getByRole('combobox', { name: 'AI model' }) as HTMLSelectElement).value).toBe('gpt-4.1-mini');
    expect(screen.queryByRole('textbox', { name: 'Custom AI model' })).toBeNull();
  });
  it('ignores a closed dialog’s late model result after a newer disconnect', async () => {
    let resolve!: (value: AiStatus) => void;
    api.model.mockImplementation(() => new Promise(r => { resolve = r; }));
    const first = render(<AiSettings status={current} enabled={true} onStatus={onStatus} onEnabled={onEnabled}/>);
    await ready();
    fireEvent.change(screen.getByRole('combobox', { name: 'AI model' }), { target: { value: 'gpt-4.1-mini' } });
    fireEvent.click(screen.getByRole('button', { name: 'Use selected model' }));
    const signal = api.model.mock.calls[0][1] as AbortSignal;
    first.unmount();
    expect(signal.aborted).toBe(true);
    const disconnected: AiStatus = { ...next, configured: false, source: 'none' };
    api.disconnect.mockResolvedValue(disconnected);
    render(<AiSettings status={current} enabled={true} onStatus={onStatus} onEnabled={onEnabled}/>);
    await ready();
    fireEvent.click(screen.getByRole('button', { name: 'Disconnect AI' }));
    await waitFor(() => expect(onStatus).toHaveBeenCalledWith(disconnected));
    await act(async () => resolve(next));
    expect(onStatus).toHaveBeenCalledTimes(1);
    expect(onEnabled).toHaveBeenCalledExactlyOnceWith(false);
  });
  it('refreshes authoritative model state when settings reopen', async () => {
    api.get.mockResolvedValue(next);
    render(<AiSettings status={current} enabled={true} onStatus={onStatus} onEnabled={onEnabled}/>);
    await ready();
    expect(onStatus).toHaveBeenCalledWith(next);
    expect(onEnabled).not.toHaveBeenCalled();
  });
  it('uses an existing Anthropic key to check a custom Claude model', async () => {
    api.get.mockResolvedValue(claude);
    api.model.mockResolvedValue({ ...claude, model: 'custom-claude-model' });
    render(<AiSettings status={claude} enabled={true} onStatus={onStatus} onEnabled={onEnabled}/>);
    await ready();
    expect(screen.getByText('Claude configured')).toBeTruthy();
    expect(screen.queryByLabelText('Anthropic API key')).toBeNull();
    fireEvent.change(screen.getByRole('combobox', { name: 'AI model' }), { target: { value: 'custom' } });
    fireEvent.change(screen.getByRole('textbox', { name: 'Custom AI model' }), { target: { value: ' custom-claude-model ' } });
    fireEvent.click(screen.getByRole('button', { name: 'Use selected model' }));
    await waitFor(() => expect(api.model).toHaveBeenCalledWith('custom-claude-model', expect.any(AbortSignal)));
    expect(api.connect).not.toHaveBeenCalled();
    expect(onEnabled).not.toHaveBeenCalled();
  });
  it('refreshes authoritative provider state even when the other fields match', async () => {
    const refreshed: AiStatus = { ...current, provider: 'anthropic' };
    api.get.mockResolvedValue(refreshed);
    render(<AiSettings status={current} enabled={true} onStatus={onStatus} onEnabled={onEnabled}/>);
    await ready();
    expect(onStatus).toHaveBeenCalledWith(refreshed);
    expect(onEnabled).not.toHaveBeenCalled();
  });
  it('ignores an authoritative status refresh after the dialog closes', async () => {
    let resolve!: (value: AiStatus) => void;
    api.get.mockImplementation(() => new Promise(r => { resolve = r; }));
    const { unmount } = render(<AiSettings status={current} enabled={true} onStatus={onStatus} onEnabled={onEnabled}/>);
    const signal = api.get.mock.calls[0][0] as AbortSignal;
    expect((screen.getByRole('combobox', { name: 'AI provider' }) as HTMLSelectElement).disabled).toBe(true);
    unmount();
    expect(signal.aborted).toBe(true);
    await act(async () => resolve(claude));
    expect(onStatus).not.toHaveBeenCalled();
    expect(onEnabled).not.toHaveBeenCalled();
  });
});
