import React from 'react';
import {beforeEach,describe,it,expect,vi} from 'vitest';
import {act,render,screen,fireEvent,waitFor,within} from '@testing-library/react';
import App from '../src/App';
import {createWorkspace} from '../src/lib/seed';
import {draftAnswer} from '../src/lib/engine';
import type {AiResponse,AiStatus} from '../src/lib/aiTypes';
import type {Workspace} from '../src/lib/types';
const api=vi.hoisted(()=>({get:vi.fn(),answer:vi.fn(),connect:vi.fn(),disconnect:vi.fn(),model:vi.fn()}));
vi.mock('../src/lib/aiClient',()=>({EMPTY_AI_STATUS:{configured:false,provider:'openai',model:'gpt-4.1-mini',source:'none'},getAiStatus:api.get,requestAiAnswer:api.answer,connectAi:api.connect,disconnectAi:api.disconnect,setAiModel:api.model}));
vi.mock('../src/components/AnswerCanvas',()=>({default:({workspace,onDraft,onSelect}:{workspace:Workspace;onDraft:(id:string)=>void;onSelect:(id:string)=>void})=><div>{workspace.questions.map(q=><button key={q.id} onClick={()=>onDraft(q.id)}>Draft {q.id}</button>)}{workspace.cards.map(c=><button key={c.id} onClick={()=>onSelect(c.id)}>Open {c.entityId}</button>)}</div>}));
const connected:AiStatus={configured:true,provider:'openai',model:'gpt-4.1-mini',source:'session'};
const key='test-only-credential-not-a-real-api-key';
function result():AiResponse {const w=createWorkspace(),q=w.questions.find(q=>q.id==='q-04')!,d=draftAnswer(q,w.products);return {provider:'openai',model:'gpt-4.1-mini',generatedAt:new Date().toISOString(),answer:{kind:'answer',title:'An AI draft for Cloud Cream',text:'Cloud Cream costs £38. If your current moisturiser works, keep it. The recorded note is a starting point for your decision.',decision:d.decision!,productIds:['cloud-cream'],sourceIds:['product:cloud-cream','note:maya-judgement'],missingEvidence:[]}};}
function saved():Workspace{return JSON.parse(localStorage.getItem('maya-answer-canvas-v1')!);}
async function ready(){await waitFor(()=>expect(screen.getByRole('button',{name:'AI enabled',exact:true})).toBeTruthy());}
function send(){fireEvent.change(screen.getByRole('textbox',{name:'Message Maya'}),{target:{value:'Is Cloud Cream worth £38?'}});fireEvent.click(screen.getByRole('button',{name:'Send message'}));}
function withExisting(){const w=createWorkspace(),q=w.questions.find(q=>q.id==='q-04')!,draft=draftAnswer(q,w.products);w.drafts=[draft];w.cards.push({id:'test-draft-card',kind:'draft',entityId:draft.id,x:800,y:35});localStorage.setItem('maya-answer-canvas-v1',JSON.stringify(w));return draft;}
beforeEach(()=>{vi.clearAllMocks();api.get.mockResolvedValue(connected);api.answer.mockResolvedValue(result());api.connect.mockResolvedValue(connected);api.model.mockResolvedValue(connected);api.disconnect.mockResolvedValue({...connected,configured:false,source:'none'});});
describe('Live AI workflow with a mocked provider boundary',()=>{
 it('uses Claude for a draft, persists its origin and keeps it unapproved',async()=>{const status:AiStatus={...connected,provider:'anthropic',model:'claude-haiku-4-5-20251001'};api.get.mockResolvedValue(status);api.answer.mockResolvedValue({...result(),provider:'anthropic',model:status.model});render(<App/>);await ready();fireEvent.click(screen.getByRole('button',{name:'Draft q-04'}));await waitFor(()=>expect(saved().drafts).toHaveLength(1));expect(saved().drafts[0].ai?.provider).toBe('anthropic');expect(saved().drafts[0].status).toBe('draft');expect(saved().drafts[0].approvedAt).toBeUndefined();});
 it('shows a Claude failure without saving an answer or falling back to local text',async()=>{api.get.mockResolvedValue({...connected,provider:'anthropic',model:'claude-haiku-4-5-20251001'});api.answer.mockRejectedValue(new Error('Claude is temporarily overloaded. Try again later.'));render(<App/>);await ready();fireEvent.click(screen.getByRole('button',{name:'Chat with Maya',exact:true}));send();await screen.findByText('Claude is temporarily overloaded. Try again later.');expect(JSON.parse(localStorage.getItem('maya-chat-v1')!)).toHaveLength(1);expect(api.answer).toHaveBeenCalledTimes(1);expect(saved().drafts).toHaveLength(0);});

 it('connects through the password form without saving a key in workspace or chat storage',async()=>{api.get.mockResolvedValue({...connected,configured:false,source:'none'});render(<App/>);fireEvent.click(screen.getByRole('button',{name:'Set up AI',exact:true}));await waitFor(()=>expect((screen.getByLabelText('OpenAI API key') as HTMLInputElement).disabled).toBe(false));fireEvent.change(screen.getByLabelText('OpenAI API key'),{target:{value:key}});fireEvent.click(screen.getByRole('button',{name:'Connect and enable AI'}));await waitFor(()=>expect(api.connect).toHaveBeenCalledWith(key,'gpt-4.1-mini',expect.any(AbortSignal),'openai'));expect((screen.queryByLabelText('OpenAI API key') as HTMLInputElement|null)?.value||'').toBe('');expect(Object.keys(localStorage).map(k=>localStorage.getItem(k)).join('')).not.toContain(key);expect(screen.getByText('OpenAI configured')).toBeTruthy();});
 it('creates a sourced AI draft without approving or publishing it',async()=>{render(<App/>);await ready();fireEvent.click(screen.getByRole('button',{name:'Draft q-04'}));await waitFor(()=>expect(saved().drafts).toHaveLength(1));const d=saved().drafts[0];expect(d.mode).toBe('AI suggestion');expect(d.status).toBe('draft');expect(d.ai?.model).toBe('gpt-4.1-mini');expect(d.productRevisions['cloud-cream']).toBe(1);expect(d.sourceRefs.some(s=>s.excerpt.includes('Cloud Cream'))).toBe(true);expect(d.approvedAt).toBeUndefined();expect(api.answer.mock.calls[0][0].evidence).toBeTruthy();});
 it('does not let a fluent AI answer bypass the Barrier Cream evidence hold',async()=>{render(<App/>);await ready();fireEvent.click(screen.getByRole('button',{name:'Draft q-05'}));await waitFor(()=>expect(saved().drafts).toHaveLength(1));expect(saved().drafts[0].ai?.missingEvidence.length).toBeGreaterThan(0);expect((screen.getByRole('button',{name:'Approve answer'}) as HTMLButtonElement).disabled).toBe(true);});
 it('shows an AI failure with retry and never substitutes a local answer',async()=>{api.answer.mockRejectedValueOnce(new Error('OpenAI has no available quota.'));render(<App/>);await ready();fireEvent.click(screen.getByRole('button',{name:'Chat with Maya',exact:true}));send();await screen.findByText('OpenAI has no available quota.');expect(JSON.parse(localStorage.getItem('maya-chat-v1')!)).toHaveLength(1);fireEvent.click(screen.getByRole('button',{name:'Retry AI answer'}));await waitFor(()=>expect(JSON.parse(localStorage.getItem('maya-chat-v1')!)).toHaveLength(2));const messages=JSON.parse(localStorage.getItem('maya-chat-v1')!);expect(messages[1].origin).toBe('ai');expect(messages.filter((m:{role:string})=>m.role==='user')).toHaveLength(1);expect(saved().drafts).toHaveLength(0);});
 it('ignores a cancelled late response after clearing chat',async()=>{let resolve!:(value:AiResponse)=>void;api.answer.mockImplementation(()=>new Promise(r=>{resolve=r;}));render(<App/>);await ready();fireEvent.click(screen.getByRole('button',{name:'Chat with Maya',exact:true}));send();expect(screen.getByText(/AI is checking the evidence/)).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Clear chat'}));await act(async()=>resolve(result()));expect(JSON.parse(localStorage.getItem('maya-chat-v1')!)).toEqual([]);expect(api.answer.mock.calls[0][1].aborted).toBe(true);});
 it('keeps a composed chat message while a draft request is running',async()=>{let resolve!:(value:AiResponse)=>void;api.answer.mockImplementation(()=>new Promise(r=>{resolve=r;}));render(<App/>);await ready();fireEvent.click(screen.getByRole('button',{name:'Draft q-04'}));fireEvent.click(screen.getByRole('button',{name:'Chat with Maya',exact:true}));const input=screen.getByRole('textbox',{name:'Message Maya'});fireEvent.change(input,{target:{value:'Keep this question while the draft runs.'}});expect((screen.getByRole('button',{name:'Send message'}) as HTMLButtonElement).disabled).toBe(true);fireEvent.keyDown(input,{key:'Enter'});expect((input as HTMLTextAreaElement).value).toBe('Keep this question while the draft runs.');expect(api.answer).toHaveBeenCalledTimes(1);await act(async()=>resolve(result()));});
 it('preserves edits made while AI is generating a replacement',async()=>{const draft=withExisting();let resolve!:(value:AiResponse)=>void;api.answer.mockImplementation(()=>new Promise(r=>{resolve=r;}));render(<App/>);await ready();fireEvent.click(screen.getByRole('button',{name:`Open ${draft.id}`}));fireEvent.click(screen.getByRole('button',{name:'Suggest with AI'}));fireEvent.change(screen.getByRole('textbox',{name:'Your answer'}),{target:{value:'My own newer wording should survive.'}});await act(async()=>resolve(result()));expect(saved().drafts[0].text).toBe('My own newer wording should survive.');expect(screen.queryByRole('dialog',{name:'Review AI suggestion'})).toBeNull();expect(screen.getByText(/changed while AI was working/)).toBeTruthy();});
 it('requires an explicit comparison choice before replacing existing wording',async()=>{const draft=withExisting();render(<App/>);await ready();fireEvent.click(screen.getByRole('button',{name:`Open ${draft.id}`}));fireEvent.click(screen.getByRole('button',{name:'Suggest with AI'}));const dialog=await screen.findByRole('dialog',{name:'Review AI suggestion'});expect(saved().drafts[0].text).toBe(draft.text);fireEvent.click(within(dialog).getByRole('button',{name:'Use AI suggestion'}));expect(saved().drafts[0].text).toBe(result().answer.text);expect(saved().drafts[0].status).toBe('draft');expect(saved().drafts[0].history?.some(item=>item.snapshot.text===draft.text)).toBe(true);});
});
