import React from 'react';
import {describe,it,expect,vi} from 'vitest';
import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import App from '../src/App';
import type {Workspace} from '../src/lib/types';
vi.mock('../src/components/AnswerCanvas',()=>({default:function MockCanvas({workspace,onSelect}:{workspace:Workspace;onSelect:(id:string)=>void}){const [query,setQuery]=React.useState('');return <div><input id="canvas-card-search" aria-label="Find a card" value={query} onChange={event=>setQuery(event.target.value)}/>{query&&<button onClick={()=>{onSelect(workspace.cards[0].id);setQuery('');}}>Go to search result</button>}{workspace.cards.map(c=><button key={c.id} onClick={()=>onSelect(c.id)}>Open {c.entityId}</button>)}</div>;}}));
describe('Canvas shell accessibility and layout state',()=>{
 it('expands the workspace without changing the board and restores the normal layout',()=>{render(<App/>);const before=localStorage.getItem('maya-answer-canvas-v1');fireEvent.click(screen.getByRole('button',{name:'Expand canvas'}));expect(document.querySelector('.canvas-workspace--expanded')).not.toBeNull();expect(screen.getByRole('button',{name:'Exit expanded view'}).getAttribute('aria-pressed')).toBe('true');expect(localStorage.getItem('maya-answer-canvas-v1')).toBe(before);fireEvent.click(screen.getByRole('button',{name:'Exit expanded view'}));expect(document.querySelector('.canvas-workspace--expanded')).toBeNull();});
 it('keeps navigation named even when its visible labels collapse and marks the current destination',()=>{render(<App/>);document.querySelectorAll('.sidebar nav button > span').forEach(span=>(span as HTMLElement).style.display='none');const nav=screen.getByRole('button',{name:'Audience questions',exact:true});expect(screen.getByRole('button',{name:'Answer canvas',exact:true}).getAttribute('aria-current')).toBe('page');fireEvent.click(nav);expect(nav.getAttribute('aria-current')).toBe('page');expect(screen.getByRole('button',{name:'Answer canvas',exact:true}).getAttribute('aria-current')).toBeNull();});
 it('moves keyboard focus into details and Escape returns it to the originating card',async()=>{render(<App/>);const trigger=screen.getByRole('button',{name:'Open q-04'});trigger.focus();fireEvent.click(trigger);const panel=screen.getByRole('complementary',{name:'Card details'});await waitFor(()=>expect(document.activeElement).toBe(panel));fireEvent.keyDown(panel,{key:'Escape'});expect(screen.queryByRole('complementary',{name:'Card details'})).toBeNull();expect(document.activeElement).toBe(trigger);fireEvent.click(screen.getByRole('button',{name:'Show card details'}));expect(screen.getByRole('complementary',{name:'Card details'})).toBeTruthy();});
 it('leaves expansion and details cleanly when navigating to another view',()=>{render(<App/>);fireEvent.click(screen.getByRole('button',{name:'Expand canvas'}));fireEvent.click(screen.getByRole('button',{name:'Open q-04'}));fireEvent.click(screen.getByRole('button',{name:'Audience questions',exact:true}));expect(document.querySelector('.canvas-workspace--expanded')).toBeNull();expect(screen.queryByRole('complementary',{name:'Card details'})).toBeNull();});
 it('returns focus to card search when a search result or reopen trigger has been removed',async()=>{render(<App/>);const search=screen.getByRole('textbox',{name:'Find a card'});fireEvent.change(search,{target:{value:'Sarah'}});const result=screen.getByRole('button',{name:'Go to search result'});result.focus();fireEvent.click(result);const panel=screen.getByRole('complementary',{name:'Card details'});await waitFor(()=>expect(document.activeElement).toBe(panel));expect(result.isConnected).toBe(false);fireEvent.keyDown(panel,{key:'Escape'});expect(document.activeElement).toBe(search);const reopen=screen.getByRole('button',{name:'Show card details'});reopen.focus();fireEvent.click(reopen);const reopenedPanel=screen.getByRole('complementary',{name:'Card details'});await waitFor(()=>expect(document.activeElement).toBe(reopenedPanel));expect(reopen.isConnected).toBe(false);fireEvent.keyDown(reopenedPanel,{key:'Escape'});expect(document.activeElement).toBe(search);});
});
