import { useState } from 'react';
import { ArrowRight, ArrowUpRight, BookOpen, Link2, Search, ShieldCheck } from 'lucide-react';
import type { Draft, Workspace } from '../lib/types';
import type { DecisionProfile } from '../lib/decisionTypes';
import { validateDraft } from '../lib/engine';
import { DecisionSummary } from './DecisionProfile';
import './ReusableAnswers.css';

type DecisionDraft = Draft & { decision?: DecisionProfile };
export function ReuseSuggestions({candidates,onReuse}:{candidates:DecisionDraft[];onReuse:(draft:Draft)=>void}) {
 if(!candidates.length)return null;
 return <section className="reuse-suggestions" aria-label="Reviewed starting points"><div className="reuse-heading"><BookOpen size={16}/><h3>A reviewed starting point</h3></div><p>Same product and decision topic. Check this follower’s budget, preferences and existing routine before using it.</p>{candidates.slice(0,3).map(d=><article key={d.id}><strong>{d.title}</strong>{d.decision&&<span className="reuse-call">{d.decision.verdict}</span>}<button className="secondary full" onClick={()=>onReuse(d)}>Use as starting point<ArrowRight size={15}/></button></article>)}</section>;
}
export default function AnswerLibrary({workspace,onReview,onShare,onOpen,onStart}:{workspace:Workspace;onReview:(d:Draft)=>void;onShare:(d:Draft)=>void;onOpen:(d:Draft)=>void;onStart:()=>void}) {
 const [query,setQuery]=useState('');
 const answers=workspace.drafts.filter(d=>d.status==='approved'||d.status==='published') as DecisionDraft[];
 const shown=answers.filter(d=>`${d.title} ${d.text} ${d.decision?.suits||''} ${d.decision?.skipIf||''} ${d.decision?.verdict||''} ${d.decision?.unknowns||''}`.toLowerCase().includes(query.toLowerCase()));
 return <div className="answer-library"><div className="list-toolbar"><div><span className="eyebrow">REVIEW ONCE. REUSE WITH CARE.</span><p className="subtle">Approved decisions, with their limits intact. Shared cards are copies of a published version.</p></div><span className="badge green">{answers.length} reviewed {answers.length===1?'answer':'answers'}</span></div><label className="search-field library-search"><Search size={16}/><input aria-label="Search approved advice" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a product, decision or preference…"/></label>{!answers.length?<div className="empty-state published-empty"><BookOpen size={38} strokeWidth={1.2}/><span className="eyebrow">BUILD YOUR FIRST REUSABLE ANSWER</span><h2>Your judgement, ready for next time.</h2><p>Review a draft, its audience and its limits. Approve it to keep a starting point for similar questions, then publish a card followers can save.</p><button className="primary" onClick={onStart}>Review the first answer<ArrowRight size={15}/></button></div>:!shown.length?<div className="empty-state"><Search size={28}/><h3>No reviewed answers match.</h3><p>Try a product name or a shorter phrase.</p></div>:<div className="decision-library-grid">{shown.map(d=>{const problems=validateDraft(d,workspace);return <article className="decision-library-card" key={d.id}><div className="decision-library-status"><ShieldCheck size={15}/><span>{problems.length?'Needs a new review':d.status==='published'?'Published locally':'Approved locally'}</span></div><h2>{d.title}</h2><p className="decision-library-copy">{d.text}</p>{d.decision?<DecisionSummary value={d.decision}/>:<p className="decision-legacy-note">This earlier answer has no decision details. Add them when you next review it.</p>}<div className="decision-library-actions"><button className="secondary small" onClick={()=>onReview(d)}>{d.decision?'Review on canvas':'Add decision details'}<ArrowRight size={14}/></button>{d.status==='published'&&<><button className="quiet-button" disabled={!!problems.length} onClick={()=>onOpen(d)}>Follower view<ArrowUpRight size={14}/></button><button className="icon-button" aria-label={`Share ${d.title}`} disabled={!!problems.length} onClick={()=>onShare(d)}><Link2 size={16}/></button></>}</div>{d.status==='approved'&&<p className="helper">Ready to reuse as a draft. Publish from the canvas when the follower card is ready.</p>}</article>;})}</div>}</div>;
}
